/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfacesApp;

import ArchivosCRUD.ClientesCRUD;
import Personas.Cliente;
import Trabajo.Oficios;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MADE
 */
public class Caja extends javax.swing.JPanel {

    private double totalPagar = 0;

    /**
     * Creates new form Caja
     */
    public Caja() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TablonCaja = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        IdClienteTXT = new javax.swing.JTextField();
        BuscarIdCliente = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        ValorTXT = new javax.swing.JLabel();
        Cobrar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaTrabajos = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(800, 700));

        TablonCaja.setBackground(new java.awt.Color(255, 255, 255));
        TablonCaja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TablonCaja.setPreferredSize(new java.awt.Dimension(800, 700));
        TablonCaja.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jLabel15.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("caja");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TablonCaja.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 798, 65));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IDENTIFICACION DEL CLIENTE:");
        TablonCaja.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 72, 259, 61));

        IdClienteTXT.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        IdClienteTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdClienteTXTActionPerformed(evt);
            }
        });
        TablonCaja.add(IdClienteTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 72, 288, 61));

        BuscarIdCliente.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        BuscarIdCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BuscarIdCliente.setText("BUSCAR");
        BuscarIdCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BuscarIdCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarIdClienteMouseClicked(evt);
            }
        });
        TablonCaja.add(BuscarIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 72, 214, 61));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel23.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("valor total:");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ValorTXT.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        ValorTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ValorTXT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Cobrar.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        Cobrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cobrar.setText("cobrar");
        Cobrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cobrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CobrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ValorTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(Cobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValorTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        TablonCaja.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 488, -1, -1));

        TablaTrabajos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaTrabajos.setEnabled(false);
        jScrollPane1.setViewportView(TablaTrabajos);

        TablonCaja.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 800, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TablonCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TablonCaja, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void IdClienteTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdClienteTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdClienteTXTActionPerformed

    private void BuscarIdClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarIdClienteMouseClicked
        //Obtener el ID ingresado
        String idCliente = IdClienteTXT.getText();

        if (idCliente.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite una id", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            boolean encontrado = false;

            //Obtener la lista de clientes desde la base de datos simulada.
            ArrayList<Cliente> clientes = ClientesCRUD.Read();

            ArrayList<Oficios> oficios;

            //Crear el modelo de la tabla.
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID DEL TRABAJO");
            model.addColumn("ESTADO");
            model.addColumn("TOTAL PAGAR");

            //Buscar el cliente por ID
            for (Cliente cliente : clientes) {
                if (cliente.getId().equals(idCliente)) {
                    oficios = cliente.getOficios();

                    for (Oficios oficio : oficios) {
                        if (oficio.getEstadoTrabajo() == false && oficio.getPagado() == false) {
                            //Agregar información del trabajo a la tabla.
                            model.addRow(new Object[]{oficio.getIdTrabajo(), "FINALIZADO", oficio.cotizarPrecio()});
                            //Actualizar el total a pagar.
                            totalPagar += oficio.cotizarPrecio();
                        }
                    }

                    encontrado = true;
                    break;
                }
            }

            //Mostrar mensajes según el resultado de la búsqueda.
            if (encontrado == false) {
                JOptionPane.showMessageDialog(null, "Id del cliente no registrada", "Alerta", JOptionPane.WARNING_MESSAGE);
            }

            //Actualizar el valor total en la interfaz.
            ValorTXT.setText(totalPagar + "");
            //Establecer el modelo de la tabla.
            TablaTrabajos.setModel(model);
        }
    }//GEN-LAST:event_BuscarIdClienteMouseClicked

    private void CobrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CobrarMouseClicked
        //Obtener el ID ingresado.
        String idCliente = IdClienteTXT.getText();

        //Obtener la lista de clientes desde la base de datos simulada.
        ArrayList<Cliente> clientes = ClientesCRUD.Read();
        ArrayList<Oficios> oficios;
        boolean encontrado = false;

        //Buscar el cliente por ID.
        for (Cliente cliente : clientes) {
            if (cliente.getId().equals(idCliente)) {
                oficios = cliente.getOficios();

                //Marcar como pagados los trabajos finalizados y no pagados.
                for (Oficios oficio : oficios) {
                    if (oficio.getEstadoTrabajo() == false && oficio.getPagado() == false) {
                        oficio.setPagado(true);
                    }
                }

                //Actualizar la lista de oficios del cliente.
                cliente.setOficios(oficios);

                //Actualizar la información en la base de datos simulada.
                ClientesCRUD.Update(cliente);

                encontrado = true;
                break;
            }
        }

        //Mostrar mensajes según el resultado de la búsqueda.
        if (encontrado == false) {
            JOptionPane.showMessageDialog(null, "Id del cliente no registrada", "Alerta", JOptionPane.WARNING_MESSAGE);
        }

        //Mostrar mensaje de pago exitoso.
        JOptionPane.showMessageDialog(null, "Se ha pagado con exito", "PAGO EXITOSO", JOptionPane.OK_OPTION);
        //Ocultar el panel actual.
        this.setVisible(false);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_CobrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuscarIdCliente;
    private javax.swing.JLabel Cobrar;
    private javax.swing.JTextField IdClienteTXT;
    private javax.swing.JTable TablaTrabajos;
    private javax.swing.JPanel TablonCaja;
    private javax.swing.JLabel ValorTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
