/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfacesApp;

import ArchivosCRUD.ClientesCRUD;
import ObjetosApp.Vehiculo;
import Personas.Cliente;
import Trabajo.Oficios;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author MADE
 */
public class IniciarTrabajo extends javax.swing.JPanel {

    //Variables de clase
    private String idMecanico;
    private LocalDate fecha;
    private String codigoUnicoAUX;

    /**
     * Constructor de la clase IniciarTrabajo.
     * Inicializa la interfaz gráfica y establece la fecha actual.
     */
    public IniciarTrabajo() {
        initComponents();
        fecha = LocalDate.now();
        fechaProgramaJBL.setText(fecha + "");
    }

    public String getIdMecanico() {
        return idMecanico;
    }

    public void setIdMecanico(String idMecanico) {
        this.idMecanico = idMecanico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoTrabajo = new javax.swing.ButtonGroup();
        ContenedorClientes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        idClienteTXT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        catorceJBL = new javax.swing.JLabel();
        veinteJBL = new javax.swing.JLabel();
        sieteJBL = new javax.swing.JLabel();
        IniciarTrabajo = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Detalles = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        IdTrabajo = new javax.swing.JLabel();
        repMecanica = new javax.swing.JRadioButton();
        repLatoneria = new javax.swing.JRadioButton();
        revision = new javax.swing.JRadioButton();
        fechaProgramaJBL = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        vehiculosDisponibles = new javax.swing.JComboBox<>();

        ContenedorClientes.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ContenedorClientes.setPreferredSize(new java.awt.Dimension(800, 700));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INICIAR TRABAJOS");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(804, 440));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("IDENTIFICACION DEL CLIENTE (ID):");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        idClienteTXT.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        idClienteTXT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idClienteTXTFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("codigo unico de trabajo:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("tipo de trabajo:");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("plazo de tiempo:");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        catorceJBL.setBackground(new java.awt.Color(102, 255, 102));
        catorceJBL.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        catorceJBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catorceJBL.setText("14 dias");
        catorceJBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        catorceJBL.setOpaque(true);

        veinteJBL.setBackground(new java.awt.Color(102, 255, 102));
        veinteJBL.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        veinteJBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        veinteJBL.setText("21 dias");
        veinteJBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sieteJBL.setBackground(new java.awt.Color(102, 255, 102));
        sieteJBL.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        sieteJBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sieteJBL.setText("7 dias");
        sieteJBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        IniciarTrabajo.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        IniciarTrabajo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IniciarTrabajo.setText("EMPEZAR TRABAJO");
        IniciarTrabajo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        IniciarTrabajo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IniciarTrabajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarTrabajoMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("detalles:");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Detalles.setColumns(20);
        Detalles.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        Detalles.setRows(5);
        jScrollPane1.setViewportView(Detalles);

        jLabel16.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("fecha de inicio");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        IdTrabajo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tipoTrabajo.add(repMecanica);
        repMecanica.setSelected(true);
        repMecanica.setText("REPARACION MECANICA");
        repMecanica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                repMecanicaMouseClicked(evt);
            }
        });

        tipoTrabajo.add(repLatoneria);
        repLatoneria.setText("REPARACION LATONERIA");
        repLatoneria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                repLatoneriaMouseClicked(evt);
            }
        });
        repLatoneria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repLatoneriaActionPerformed(evt);
            }
        });

        tipoTrabajo.add(revision);
        revision.setText("REVISION");
        revision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                revisionMouseClicked(evt);
            }
        });

        fechaProgramaJBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fechaProgramaJBL.setText("dd/mm/yyyy");

        jLabel11.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("vehiculo:");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        vehiculosDisponibles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "item 1" }));
        vehiculosDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiculosDisponiblesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(IniciarTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fechaProgramaJBL, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vehiculosDisponibles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(repMecanica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(catorceJBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(IdTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(veinteJBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(repLatoneria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sieteJBL, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(revision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(idClienteTXT))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(idClienteTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(IdTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repMecanica)
                    .addComponent(repLatoneria)
                    .addComponent(revision))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(vehiculosDisponibles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catorceJBL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veinteJBL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sieteJBL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaProgramaJBL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(IniciarTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout ContenedorClientesLayout = new javax.swing.GroupLayout(ContenedorClientes);
        ContenedorClientes.setLayout(ContenedorClientesLayout);
        ContenedorClientesLayout.setHorizontalGroup(
            ContenedorClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        ContenedorClientesLayout.setVerticalGroup(
            ContenedorClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorClientesLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(ContenedorClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarTrabajoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarTrabajoMouseClicked

        //Obtiene los datos del formulario.
        String idCliente = idClienteTXT.getText();
        String tipoTrabajo = "";
        String detalles = Detalles.getText();
        int plazo = 0;

        //Determina el tipo de trabajo seleccionado.
        if (repMecanica.isSelected()) {
            tipoTrabajo = "REPARACION MECANICA";
            plazo = 14;
        } else if (repLatoneria.isSelected()) {
            tipoTrabajo = "REPARACION LATONERIA";
            plazo = 21;
        } else if (revision.isSelected()) {
            tipoTrabajo = "REVISION";
            plazo = 7;
        }

        //Valida la entrada del usuario.
        if (idCliente.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar todos los datos correspondientes", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            //Busca el cliente en la base de datos.
            ArrayList<Cliente> clientes = ClientesCRUD.Read();
            ArrayList<Oficios> aux;

            for (Cliente cliente : clientes) {
                if (cliente.getId().equals(idCliente)) {
                    //Actualiza la lista de oficios del cliente.
                    aux = cliente.getOficios();
                    Oficios ofAUX = new Oficios(codigoUnicoAUX, tipoTrabajo, fecha, plazo, idCliente, idMecanico, detalles);
                    aux.add(ofAUX);
                    cliente.setOficios(aux);
                    ClientesCRUD.Update(cliente);
                    System.out.println(ofAUX.toString());
                    JOptionPane.showMessageDialog(null, "El trabajo se ha creado correctamente", "TRABAJO", JOptionPane.OK_OPTION);
                }
            }

            //Limpia los campos del formulario.
            idClienteTXT.setText("");
            Detalles.setText("");
        }

        //Oculta el panel y actualiza la interfaz.
        this.setVisible(false);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_IniciarTrabajoMouseClicked

    private void repMecanicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repMecanicaMouseClicked
        sieteJBL.setOpaque(false);
        catorceJBL.setOpaque(true);
        veinteJBL.setOpaque(false);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_repMecanicaMouseClicked

    private void repLatoneriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repLatoneriaMouseClicked
        sieteJBL.setOpaque(false);
        catorceJBL.setOpaque(false);
        veinteJBL.setOpaque(true);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_repLatoneriaMouseClicked

    private void revisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_revisionMouseClicked
        sieteJBL.setOpaque(true);
        catorceJBL.setOpaque(false);
        veinteJBL.setOpaque(false);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_revisionMouseClicked

    private void idClienteTXTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idClienteTXTFocusLost

        //Obtiene el ID del cliente ingresado por el usuario.
        String idAux = idClienteTXT.getText();

        //Inicializa el contador de oficios del cliente.
        int contOficios = 0;

        //Variable para verificar si el ID del cliente existe.
        boolean existe = false;

        //Verifica si el ID del cliente no está vacío.
        if (!idAux.isEmpty()) {
            //Obtiene la lista de clientes desde la base de datos.
            ArrayList<Cliente> clientes = ClientesCRUD.Read();

            //Itera sobre la lista de clientes para encontrar el cliente con el ID proporcionado.
            for (Cliente cliente : clientes) {
                if (cliente.getId().equals(idAux)) {
                    //Actualiza el contador de oficios y el código único para el nuevo trabajo.
                    contOficios = cliente.getOficios().size();
                    codigoUnicoAUX = idAux + "-" + (contOficios + 1);
                    IdTrabajo.setText(codigoUnicoAUX);

                    //Actualiza la lista de vehículos disponibles para el cliente.
                    ArrayList<Vehiculo> vAux = cliente.getVehiculos();
                    ArrayList<String> tiposVAux = new ArrayList<>();

                    for (Vehiculo veh : vAux) {
                        tiposVAux.add(veh.getTipoVehiculo());
                    }

                    //Creamos un modelo de ComboBox y agrega los elementos del ArrayList.
                    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(tiposVAux.toArray(new String[0]));
                    vehiculosDisponibles.setModel(model);

                    //Indicamos que el ID del cliente existe.
                    existe = true;
                }
            }

            //Si el ID del cliente no existe, muestra un mensaje de advertencia.
            if (!existe) {
                JOptionPane.showMessageDialog(null, "El ID del cliente no existe", "Alerta", JOptionPane.WARNING_MESSAGE);
                idClienteTXT.setText("");
                IdTrabajo.setText("");
            }
        } else {
            //Si el ID del cliente está vacío, limpia los campos relacionados.
            idClienteTXT.setText("");
            IdTrabajo.setText("");
        }
    }//GEN-LAST:event_idClienteTXTFocusLost

    private void repLatoneriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repLatoneriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repLatoneriaActionPerformed

    private void vehiculosDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehiculosDisponiblesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehiculosDisponiblesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContenedorClientes;
    private javax.swing.JTextArea Detalles;
    private javax.swing.JLabel IdTrabajo;
    private javax.swing.JLabel IniciarTrabajo;
    private javax.swing.JLabel catorceJBL;
    private javax.swing.JLabel fechaProgramaJBL;
    private javax.swing.JTextField idClienteTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton repLatoneria;
    private javax.swing.JRadioButton repMecanica;
    private javax.swing.JRadioButton revision;
    private javax.swing.JLabel sieteJBL;
    private javax.swing.ButtonGroup tipoTrabajo;
    private javax.swing.JComboBox<String> vehiculosDisponibles;
    private javax.swing.JLabel veinteJBL;
    // End of variables declaration//GEN-END:variables
}
