/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfacesApp;

import ArchivosCRUD.ClientesCRUD;
import Personas.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author MADE
 */
public class ModificarCliente extends javax.swing.JPanel {

    private String idCliente;
    private Cliente clienteActual;
   
    public ModificarCliente() {
        initComponents();
    }

    public String getIdCliente() {
        return idCliente;
    }

    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
        //Cargamos la información.
        cargarInformacionCliente();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Opciones = new javax.swing.ButtonGroup();
        ContenedorRegistroIn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Actualizar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Placa = new javax.swing.JLabel();
        Tipo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BotonNombre = new javax.swing.JRadioButton();
        BotonPlaca = new javax.swing.JRadioButton();
        BotonTipo = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        CambioTXT = new javax.swing.JTextField();

        ContenedorRegistroIn.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorRegistroIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ContenedorRegistroIn.setPreferredSize(new java.awt.Dimension(799, 699));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("modificar clientes");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NOMBRE:");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Actualizar.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        Actualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Actualizar.setText("actualizar");
        Actualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PLACA DEL VEHICULO:");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("TIPO DE VEHICULO:");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Nombre.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Placa.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        Placa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Placa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Tipo.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        Tipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("modificacion:");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Opciones.add(BotonNombre);
        BotonNombre.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        BotonNombre.setText("nombre");
        BotonNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNombreActionPerformed(evt);
            }
        });

        Opciones.add(BotonPlaca);
        BotonPlaca.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        BotonPlaca.setText("placa del vehiculo");
        BotonPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPlacaActionPerformed(evt);
            }
        });

        Opciones.add(BotonTipo);
        BotonTipo.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        BotonTipo.setText("tipo vehiculo");
        BotonTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTipoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("cambio:");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout ContenedorRegistroInLayout = new javax.swing.GroupLayout(ContenedorRegistroIn);
        ContenedorRegistroIn.setLayout(ContenedorRegistroInLayout);
        ContenedorRegistroInLayout.setHorizontalGroup(
            ContenedorRegistroInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ContenedorRegistroInLayout.createSequentialGroup()
                .addGroup(ContenedorRegistroInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorRegistroInLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(ContenedorRegistroInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContenedorRegistroInLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ContenedorRegistroInLayout.createSequentialGroup()
                                .addGroup(ContenedorRegistroInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                                .addGap(32, 32, 32)
                                .addGroup(ContenedorRegistroInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(ContenedorRegistroInLayout.createSequentialGroup()
                                        .addComponent(BotonNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)
                                        .addComponent(BotonPlaca)
                                        .addGap(49, 49, 49)
                                        .addComponent(BotonTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CambioTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Placa, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(ContenedorRegistroInLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        ContenedorRegistroInLayout.setVerticalGroup(
            ContenedorRegistroInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorRegistroInLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ContenedorRegistroInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(ContenedorRegistroInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Placa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(ContenedorRegistroInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(ContenedorRegistroInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorRegistroInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotonTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(ContenedorRegistroInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CambioTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                .addGap(74, 74, 74)
                .addComponent(Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ContenedorRegistroIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(ContenedorRegistroIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
   
    
    private void ActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarMouseClicked
        //Obtener el valor de CambioTXT
        String Cambio = CambioTXT.getText();

        //Validar si se ingresó un valor.
        if (Cambio.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor para la actualización.", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            //Actualizar la información del cliente según la opción seleccionada.
            //Verificar qué botón de modificación está seleccionado.
             if (BotonNombre.isSelected()) {
                 //Actualizar el nombre del cliente con nuevoValor.
                 clienteActual.setNombre(Cambio);
             } else if (BotonPlaca.isSelected()) {
                 //Actualizar la placa del vehículo con nuevoValor.
                 clienteActual.getVehiculos().get(0).setPlaca(Cambio);
             } else if (BotonTipo.isSelected()) {
                 //Actualizar el tipo de vehículo con nuevoValor.
                 clienteActual.getVehiculos().get(0).setTipoVehiculo(Cambio);
             }

             //Luego de actualizar la información, guardarmos el cliente actualizado.
             ClientesCRUD.Update(clienteActual);

             JOptionPane.showMessageDialog(null, "Cliente actualizado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
        
        this.setVisible(false);
        this.revalidate();
        this.repaint();
        
    }//GEN-LAST:event_ActualizarMouseClicked

    private void BotonNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonNombreActionPerformed

    private void BotonTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonTipoActionPerformed

    private void BotonPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonPlacaActionPerformed

    
    //Método para cargar la información del cliente actual.
    private void cargarInformacionCliente() {
        //Obtener la lista de clientes desde el archivo.
        for (Cliente cliente : ClientesCRUD.Read()) {
            if (cliente.getId().equals(idCliente)) {
                //Asignar el cliente actual.
                clienteActual = cliente;
                
                //Mostrar la información en los JLabel correspondientes.
                Nombre.setText(cliente.getNombre());
                Placa.setText(cliente.getVehiculos().get(0).getPlaca());
                Tipo.setText(cliente.getVehiculos().get(0).getTipoVehiculo());

                break;
            }
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Actualizar;
    private javax.swing.JRadioButton BotonNombre;
    private javax.swing.JRadioButton BotonPlaca;
    private javax.swing.JRadioButton BotonTipo;
    private javax.swing.JTextField CambioTXT;
    private javax.swing.JPanel ContenedorRegistroIn;
    private javax.swing.JLabel Nombre;
    private javax.swing.ButtonGroup Opciones;
    private javax.swing.JLabel Placa;
    private javax.swing.JLabel Tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
