/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfacesApp;

import ArchivosCRUD.InventarioCRUD;
import ObjetosApp.Inventario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mondongo
 */
public class TablonInventario extends javax.swing.JPanel {

    /**
     * Creates new form TablonInventario
     */
    public TablonInventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenedorInventario = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        productoNameTXT = new javax.swing.JTextField();
        Registro = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BuscarProducto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPRODUCTOS = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        MostrarBTN = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        ContenedorInventario.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorInventario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ContenedorInventario.setPreferredSize(new java.awt.Dimension(800, 700));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingreso.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SECCION DE INVENTARIO");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Buscar producto:");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        productoNameTXT.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        productoNameTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoNameTXTActionPerformed(evt);
            }
        });

        Registro.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        Registro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Registro.setText("REGISTRAR producto");
        Registro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Registro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistroMouseClicked(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfacesApp/IMAGENES2/NUEVO.png"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BuscarProducto.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        BuscarProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BuscarProducto.setText("BUSCAR");
        BuscarProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BuscarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarProductoMouseClicked(evt);
            }
        });

        tablaPRODUCTOS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tablaPRODUCTOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Cantidad", "Precio Unidad"
            }
        ));
        tablaPRODUCTOS.setEnabled(false);
        jScrollPane1.setViewportView(tablaPRODUCTOS);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfacesApp/IMAGENES2/NUEVO.png"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        MostrarBTN.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        MostrarBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MostrarBTN.setText("MOSTRAR TODOS LOS productos");
        MostrarBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MostrarBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MostrarBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MostrarBTNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ContenedorInventarioLayout = new javax.swing.GroupLayout(ContenedorInventario);
        ContenedorInventario.setLayout(ContenedorInventarioLayout);
        ContenedorInventarioLayout.setHorizontalGroup(
            ContenedorInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ContenedorInventarioLayout.createSequentialGroup()
                .addGroup(ContenedorInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorInventarioLayout.createSequentialGroup()
                        .addGroup(ContenedorInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ContenedorInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Registro, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(ContenedorInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContenedorInventarioLayout.createSequentialGroup()
                                .addComponent(productoNameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BuscarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                            .addGroup(ContenedorInventarioLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(ContenedorInventarioLayout.createSequentialGroup()
                        .addGroup(ContenedorInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ContenedorInventarioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(MostrarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ContenedorInventarioLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ContenedorInventarioLayout.setVerticalGroup(
            ContenedorInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorInventarioLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(ContenedorInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BuscarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productoNameTXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContenedorInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addComponent(Registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ContenedorInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MostrarBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ContenedorInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void productoNameTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoNameTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productoNameTXTActionPerformed

    private void RegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroMouseClicked
        NuevoProducto p = new NuevoProducto();
        p.setSize(800, 700);
        ContenedorInventario.removeAll();
        ContenedorInventario.add(p);
        ContenedorInventario.revalidate();
        ContenedorInventario.repaint();
        ContenedorInventario.setSize(800, 700);
        ContenedorInventario.setLocation(200, 0);
    }//GEN-LAST:event_RegistroMouseClicked

    private void BuscarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarProductoMouseClicked
        
        //Guardamos los datos ingresados.
        String idProductoAUX = productoNameTXT.getText();

        try {
            //Parseamos.
            int producto_id = Integer.parseInt(idProductoAUX);

            ArrayList<Inventario> productos = InventarioCRUD.Read();

            boolean existe = false;
            
            //Recorremos todo el arraylist para ver si esta ya registardo el producto (material).
            for (Inventario producto : productos) {
                //Si se encuentra, enviamos su id a EditarProducto.
                if (producto.getId() == producto_id) {
                    EditarProducto m = new EditarProducto();
                    m.setId_producto(producto_id);
                    m.setSize(800, 700);
                    ContenedorInventario.removeAll();
                    ContenedorInventario.add(m);
                    ContenedorInventario.revalidate();
                    ContenedorInventario.repaint();
                    ContenedorInventario.setSize(800, 700);
                    ContenedorInventario.setLocation(200, 0);
                    existe = true;
                    break;

                }

            }

            if (existe == false) {
                JOptionPane.showMessageDialog(null, "id del producto no existe", "Alerta", JOptionPane.WARNING_MESSAGE);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "id del producto debe ser numerico", "Alerta", JOptionPane.WARNING_MESSAGE);

        }
        productoNameTXT.setText("");

    }//GEN-LAST:event_BuscarProductoMouseClicked

    private void MostrarBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarBTNMouseClicked
      
        ArrayList<Inventario> datos = InventarioCRUD.Read();

        //Creamos un DefaultTableModel con datos bidimensionales y lo establecemos en la JTable.
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("Id");
        model.addColumn("Nombre");
        model.addColumn("Cantidad");
        model.addColumn("Precio Unidad");

        //Agregar las filas al modelo.
        for (Inventario fila : datos) {

            model.addRow(new Object[]{fila.getId(), fila.getNombre(), fila.getCantidad(), fila.getPrecio()});
        }
        //Setteamos la tabla. 
        tablaPRODUCTOS.setModel(model);
    }//GEN-LAST:event_MostrarBTNMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuscarProducto;
    private javax.swing.JPanel ContenedorInventario;
    private javax.swing.JLabel MostrarBTN;
    private javax.swing.JLabel Registro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField productoNameTXT;
    private javax.swing.JTable tablaPRODUCTOS;
    // End of variables declaration//GEN-END:variables
}
